#!name=Get Cookie All Time
#!desc=Start to get cookies all time, combined with their hostname.
#!tag = type=http-request, pattern=regex, script-path=javescript
#!GitHub:https://github.com/wmx2977/Surge/blob/main/Cookie_FullTime.Module
#!Raw:https://raw.githubusercontent.com/wmx2977/Surge/main/Cookie_FullTime.Module
[Script]
# > 网易云音乐(music.163.com)
网易云音乐 = type=http-request, pattern=^https:\/\/music.163.com\/weapi\/user\/level, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js

# >云闪付签到(youhui.95516.com)
云闪付签到 = type=http-request,pattern=https://youhui.95516.com/newsign/public/app/index.html,script-path=https://gitee.com/passerby-b/javascript/raw/master/unipay.js, requires-body=true

[MITM]
hostname = %APPEND% music.163.com, youhui.95516.com, 
