#!name=Cookie合集（常启）
#!desc=日常开启，获取Cookie脚本合集
#!tag = type=http-request, pattern=regex, script-path=javescript
#!GitHub:https://github.com/wmx2977/Surge/blob/main/Cookie_FullTime.Module
#!Raw:https://raw.githubusercontent.com/wmx2977/Surge/main/Cookie_FullTime.Module
[Script]
# > 网易云音乐(music.163.com)
网易云音乐 = type=http-request, pattern=^https:\/\/music.163.com\/weapi\/user\/level, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js

[MITM]
hostname = %APPEND% music.163.com, 
