#!name=Get Cookie in Need
#!desc=Start to get cookies in need, combined with their hostnames.
#!tag = type=http-request,pattern=https,script-path=javescript
#!GitHub:https://github.com/wmx2977/Surge/blob/main/Cookie_Demand.Module
#!Raw:https://raw.githubusercontent.com/wmx2977/Surge/main/Cookie_Demand.Module
[Script]
# > 百度贴吧(客户端)(c.tieba.baidu.com)
百度贴吧(客户端)http-request https?:\/\/(c\.tieba\.baidu\.com|180\.97\.\d+\.\d+)\/c\/s\/login script-path=https://raw.githubusercontent.com/NobyDa/Script/master/BDTieBa-DailyBonus/TieBa.js
# > 微博(pi.weibo.cn)
微博 = type=http-request,pattern=https:\/\/api\.weibo\.cn\/\d\/video\/machine\?gsid,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 微博钱包(pay.sc.weibo.com)
微博钱包 = type=http-request,pattern=https:\/\/pay\.sc\.weibo\.com\/aj\/mobile\/home\/welfare\/signin\/do\?,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 美团(i.meituan.com)
美团 = type=http-request,pattern=^https:\/\/i.meituan.com\/evolve\/signin\/signpost\/,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.cookie.js
# > 饿了么(h5.ele.me)
饿了么 = type=http-request,pattern=^https:\/\/h5\.ele\.me\/restapi\/eus\/v\d\/current_user$,script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemGetCookies.js
# > 滴滴出行(as.xiaojukeji.com)
滴滴出行 = type=http-request,pattern=^https:\/\/as\.xiaojukeji\.com\/ep\/as\/toggles\?,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi.js
# > 奈雪的茶(webapi.qmai.cn)
奈雪的茶 = type=http-request,pattern=^https:\/\/webapi\.qmai\.cn\/web\/cy\/v\d\/store\/template-scene,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js
# >顺丰速运（sf-integral-sign-in.weixinjia.net, mcs-mimp-web.sf-express.com）
顺丰速运 = type=http-request,pattern=^https:\/\/sf-integral-sign-in.weixinjia.net\/app\/index,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.cookie.js
# >什么值得买（*.smzdm.com）
什么值得买 = type=http-request,pattern=^https:\/\/www\.smzdm\.com\/?.?,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/smzdm/smzdm.cookie.js
# >携程旅行(m.ctrip.com)
携程旅行 = type=http-request,pattern=https:\/\/m\.ctrip\.com\/restapi\/soa2\/14946\/json\/userBaseInfo,script-path=https://raw.githubusercontent.com/iepngs/Script/master/ctrip/index.js
携程旅行 = type=http-request,pattern=https:\/\/m\.ctrip\.com\/restapi\/soa2\/14946\/json\/userBaseInfo,script-path=https://raw.githubusercontent.com/barrym-chen/Script/master/ctrip/ctrip_cookie.js
# >电信营业厅(wapside.189.cn:9001)
电信营业厅 = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10000/10000.cookie.js,requires-body=true,type=http-request,pattern=^https:\/\/wapside.189.cn:9001\/api\/home\/sign
# > 天天挖矿(operation-api.jimistore.com)
天天挖矿 = type=http-request,pattern=^https:\/\/operation-api\.jimistore\.com\/*,script-path=https://raw.githubusercontent.com/yangtingxiao/QuantumultX/master/scripts/ttwk/ttwk.js
[MITM]
hostname = %APPEND% c.tieba.baidu.com, pi.weibo.cn,pay.sc.weibo.com, i.meituan.com, h5.ele.me, as.xiaojukeji.com, webapi.qmai.cn, api.weibo.cn, pay.sc.weibo.com, sf-integral-sign-in.weixinjia.net, mcs-mimp-web.sf-express.com, *.smzdm.com,gameapi.hellobike.com, m.ctrip.com, wapside.189.cn:9001, operation-api.jimistore.com, 
