#!name=Get Cookie in Need
#!desc=Start to get cookies in need, combined with their hostnames.
#!tag = type=http-request,pattern=https,script-path=javescript
#!GitHub:https://github.com/wmx2977/Surge/blob/main/Cookie_Demand.Module
#!Raw:https://raw.githubusercontent.com/wmx2977/Surge/main/Cookie_Demand.Module
[Script]
# > 百度贴吧(tieba.baidu.com)
百度贴吧 = type=http-request,pattern=^https?:\/\/tieba\.baidu\.com\/?.?,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.cookie.js
# > 微博(pi.weibo.cn)
微博 = type=http-request,pattern=https:\/\/api\.weibo\.cn\/\d\/video\/machine\?gsid,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 微博钱包(pay.sc.weibo.com)
微博钱包 = type=http-request,pattern=https:\/\/pay\.sc\.weibo\.com\/aj\/mobile\/home\/welfare\/signin\/do\?,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 美团(i.meituan.com)
美团 = type=http-request,pattern=^https:\/\/i.meituan.com\/evolve\/signin\/signpost\/,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.cookie.js
# > 饿了么(h5.ele.me)
饿了么 = type=http-request,pattern=^https:\/\/h5\.ele\.me\/restapi\/eus\/v\d\/current_user$,script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemGetCookies.js
# > 滴滴出行(as.xiaojukeji.com)
滴滴出行 = type=http-request,pattern=^https:\/\/as\.xiaojukeji\.com\/ep\/as\/toggles\?,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi.js
# > 奈雪的茶(webapi.qmai.cn)
奈雪的茶 = type=http-request,pattern=^https:\/\/webapi\.qmai\.cn\/web\/cy\/v\d\/store\/template-scene,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js
[MITM]
hostname = %APPEND% tieba.baidu.com, pi.weibo.cn,pay.sc.weibo.com, i.meituan.com, h5.ele.me, as.xiaojukeji.com, webapi.qmai.cn, api.weibo.cn, pay.sc.weibo.com
