#!name=Tasks
#!desc=Sign-in type task request.
//name = type=cron, cronexp="cronexample", wake-system=1, timeout=180, script-path=javescript
//GitHub:https://github.com/wmx2977/Surge/blob/main/Task.Module
//raw:https://raw.githubusercontent.com/wmx2977/Surge/main/Task.Module
[Script]
# > 统一在每日 00:05 ---- 00:30 之间执行签到类任务
# > 百度贴吧(客户端)
百度贴吧(客户端) = type=cron, cronexp="0 5 */12 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/BDTieBa-DailyBonus/TieBa.js
# > 微博 & 微博钱包
微博 = type=cron,cronexp="30 10 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 美团
美团 = type=cron, cronexp="36 10 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.js
# > 饿了么
饿了么 = type=cron, cronexp="42 10 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemSign.js
饿了么 = type=cron, cronexp="42 10 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js
# > 网易云音乐
网易云音乐 = type=cron, cronexp="48 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/quanx/neteasemusic.js
# > 滴滴出行
滴滴出行 = type=cron, cronexp="0 6 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi.js
滴滴出行 = type=cron, cronexp="55 59 23 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_reward.js
# > 奈雪的茶
奈雪的茶 = type=cron, cronexp="6 6 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js
# > 支付宝
支付宝 = type=cron, cronexp="0 30 7 * * *", wake-system=1, timeout=180, script-path= https://raw.githubusercontent.com/chiupam/Proxy/master/Scripts/Alipay.js
# >顺丰速运
顺丰速运 = type=cron, cronexp="7 7 0  * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.js
# >什么值得买
什么值得买 = type=cron, cronexp="20 7 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/smzdm/smzdm.js
# >携程旅行
携程旅行 = type=cron, cronexp="10 16 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/ctrip.js
# >电信营业厅
电信营业厅 = type=cron, cronexp="10 17 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10000/10000.js
# >机场签到
机场签到 = type=cron, cronexp="45 18 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js
# >天天挖矿
天天挖矿 = type=cron, cronexp="40 19 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/yangtingxiao/QuantumultX/master/scripts/ttwk/ttwk.js
