#!name=Tasks
#!desc=Sign-in type task request.
//name = type=cron, cronexp="cronexample", wake-system=1, timeout=180, script-path=javescript
//GitHub:https://github.com/wmx2977/Surge/blob/main/Task.Module
//raw:
[Script]
# > 统一在每日 00:05 ---- 00:07 之间执行签到类任务
# > 百度贴吧
百度贴吧 = type=cron, cronexp="0 5 */12 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.js
# > 微博 & 微博钱包
微博 = type=cron,cronexp="30 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/weibo.js
# > 美团
美团 = type=cron, cronexp="36 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.js
# > 饿了么
饿了么 = type=cron, cronexp="42 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemSign.js
饿了么 = type=cron, cronexp="42 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js
# > 网易云音乐
网易云音乐 = type=cron, cronexp="48 5 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/quanx/neteasemusic.js
# > 滴滴出行
滴滴出行 = type=cron, cronexp="0 6 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi.js
滴滴出行 = type=cron, cronexp="55 59 23 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_reward.js
# > 奈雪的茶
奈雪的茶 = type=cron, cronexp="6 6 0 * * *", wake-system=1, timeout=180, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js
# > 支付宝
支付宝 = type=cron,cronexp="0 30 7 * * *", wake-system=1, timeout=180, script-path= https://raw.githubusercontent.com/chiupam/Proxy/master/Scripts/Alipay.js

